### PR TITLE
Populate .npmignore

### PR DESCRIPTION
**Pull request by Jameskmonger**

### CODE REVIEW

**Comment by dtothefp** [comment]
@Jameskmonger not sure what you mean by this PR cause the gulp directory is what drives the whole app. It all gets moved to dist in the Travis build and then published

**Comment by Jameskmonger** [comment]
Ah, okay. I didn't quite understand your build process @dtothefp. An `.npmignore` file doesn't prevent files from being pushed up to Travis, so your files will still get built. The `.npmignore` file just prevents files from being distributed through npm, and so any files that aren't required for the user to use the package should be ignored with the `.npmignore` file.

**Comment by dtothefp** [comment]
Yeh, @Jameskmonger that's actually the problem, if you look at https://github.com/dtothefp/build-boiler/blob/master/build-boiler/publish.sh, it is in the `build-boiler` directory, and all contents of that directory get built to `dist` and the contents of `dist` are `publish`ed as the npm package. 

I'm going to add docs now but the way the actual `build-boiler` module works is pre-defines a bunch of gulp tasks and allows you to hook into these tasks at the top level. In this case, the `build-boiler` repo is the top level but it is not the actual module. 

This is for a project I'm working on at work but I would like to have the community start using it at some point so I'll throw in the docs now and hopefully that will clarify some things

**Comment by dtothefp** [comment]
@Jameskmonger so I updated the docs in the top level readme. Hopefully, that clears things up if you are actually looking to use this module

**Comment by Jameskmonger** [comment]
No problem, thanks for clearing things up @dtothefp

**Pull request closed without merging**
